image: node:12

before_script:
  - npm ci

#cache:
#  paths:
#    - node_modules/

#test:lint:
#  script:
#    - npm run lint

test:node:13:
  image: node:13
  script:
    - npm run build

# LTS
test:node:12:
  script:
    - npm run build

# LTS
test:node:10:
  image: node:10
  script:
    - npm run build

# LTS
test:node:8:
  image: node:8
  script:
    - npm run build


publish:artifacts:
  stage: deploy
#  only:
#    - tags
#    - triggers
  script:
    - npm run build
  artifacts:
    paths:
      - build/
